### PR TITLE
Migrate to pypy to still have support for python 2 as sugested by moz…

### PR DESCRIPTION
**Pull request by Josue-T**
## Problem

- #32 #22

## Solution

- Use pypy which still be maintained for python 2. In long term the idea is to migrate to rust but the tokenserver-rs is not ready and we have no idea how this will evolve.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by csolisr** [comment]
Curently testing your branch in my personal server with Bullseye, [it fails apparently due to incompatible versions of packages.](https://paste.yunohost.org/raw/powofekava)

Relevant lines:

```
2022-06-06 09:06:18,840: WARNING - ERROR: requests 2.20.0 has requirement idna<2.8,>=2.5, but you'll have idna 2.8 which is incompatible.
2022-06-06 09:06:18,862: WARNING - ERROR: requests 2.20.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.
2022-06-06 09:06:18,864: WARNING - ERROR: google-api-core 1.31.6 has requirement futures>=3.2.0; python_version < "3.2", but you'll have futures 3.0.0 which is incompatible.
2022-06-06 09:06:18,866: WARNING - ERROR: tokenserver 1.5.11 has requirement configparser==3.7.4, but you'll have configparser 3.5.0 which is incompatible.
2022-06-06 09:06:18,867: WARNING - ERROR: tokenserver 1.5.11 has requirement cornice==3.5.1, but you'll have cornice 0.16.2 which is incompatible.
2022-06-06 09:06:18,876: WARNING - ERROR: tokenserver 1.5.11 has requirement gunicorn==19.10.0, but you'll have gunicorn 19.6.0 which is incompatible.
2022-06-06 09:06:18,877: WARNING - ERROR: tokenserver 1.5.11 has requirement mozsvc==0.10, but you'll have mozsvc 0.9 which is incompatible.
2022-06-06 09:06:18,879: WARNING - ERROR: tokenserver 1.5.11 has requirement pyramid==1.10.4, but you'll have pyramid 1.5.3 which is incompatible.
2022-06-06 09:06:18,881: WARNING - ERROR: tokenserver 1.5.11 has requirement requests==2.22.0, but you'll have requests 2.20.0 which is incompatible.
2022-06-06 09:06:18,889: WARNING - ERROR: tokenserver 1.5.11 has requirement WebOb==1.8.5, but you'll have webob 1.4.1 which is incompatible.
```

The UWSGI executable might not be even be generated, causing the process to fail:

```
2022-06-06 09:07:38,989: WARNING - Job for uwsgi-app@ffsync.service failed because the control process exited with error code.
2022-06-06 09:07:38,989: WARNING - See "systemctl status uwsgi-app@ffsync.service" and "journalctl -xe" for details.
2022-06-06 09:07:38,992: DEBUG - + ynh_exec_err journalctl --quiet --no-hostname --no-pager --lines=20 --unit=uwsgi-app@ffsync.service
2022-06-06 09:07:38,992: DEBUG - + [[ 6 -eq 1 ]]
2022-06-06 09:07:38,993: DEBUG - ++ journalctl --quiet --no-hostname --no-pager --lines=20 --unit=uwsgi-app@ffsync.service
2022-06-06 09:07:39,258: DEBUG - + ynh_print_err '--message=Jun 06 09:07:38 systemd[1]: Starting ffsync uWSGI app...
2022-06-06 09:07:39,284: DEBUG - Jun 06 09:07:38 systemd[3668036]: uwsgi-app@ffsync.service: Failed to locate executable /opt/yunohost/__app__/local/bin/uwsgi: No such file or directory
2022-06-06 09:07:39,284: DEBUG - Jun 06 09:07:38 systemd[3668036]: uwsgi-app@ffsync.service: Failed at step EXEC spawning /opt/yunohost/__app__/local/bin/uwsgi: No such file or directory
2022-06-06 09:07:39,285: DEBUG - Jun 06 09:07:38 systemd[1]: uwsgi-app@ffsync.service: Main process exited, code=exited, status=203/EXEC
2022-06-06 09:07:39,285: DEBUG - Jun 06 09:07:38 systemd[1]: uwsgi-app@ffsync.service: Failed with result '\''exit-code'\''.
2022-06-06 09:07:39,286: DEBUG - Jun 06 09:07:38 systemd[1]: Failed to start ffsync uWSGI app.'
```

**Comment by Josue-T** [comment]
> Curently testing your branch in my personal server with Bullseye, [it fails apparently due to incompatible versions of packages.](https://paste.yunohost.org/raw/powofekava)
> 
> Relevant lines:
> 
> ```
> 2022-06-06 09:06:18,840: WARNING - ERROR: requests 2.20.0 has requirement idna<2.8,>=2.5, but you'll have idna 2.8 which is incompatible.
> 2022-06-06 09:06:18,862: WARNING - ERROR: requests 2.20.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.
> 2022-06-06 09:06:18,864: WARNING - ERROR: google-api-core 1.31.6 has requirement futures>=3.2.0; python_version < "3.2", but you'll have futures 3.0.0 which is incompatible.
> 2022-06-06 09:06:18,866: WARNING - ERROR: tokenserver 1.5.11 has requirement configparser==3.7.4, but you'll have configparser 3.5.0 which is incompatible.
> 2022-06-06 09:06:18,867: WARNING - ERROR: tokenserver 1.5.11 has requirement cornice==3.5.1, but you'll have cornice 0.16.2 which is incompatible.
> 2022-06-06 09:06:18,876: WARNING - ERROR: tokenserver 1.5.11 has requirement gunicorn==19.10.0, but you'll have gunicorn 19.6.0 which is incompatible.
> 2022-06-06 09:06:18,877: WARNING - ERROR: tokenserver 1.5.11 has requirement mozsvc==0.10, but you'll have mozsvc 0.9 which is incompatible.
> 2022-06-06 09:06:18,879: WARNING - ERROR: tokenserver 1.5.11 has requirement pyramid==1.10.4, but you'll have pyramid 1.5.3 which is incompatible.
> 2022-06-06 09:06:18,881: WARNING - ERROR: tokenserver 1.5.11 has requirement requests==2.22.0, but you'll have requests 2.20.0 which is incompatible.
> 2022-06-06 09:06:18,889: WARNING - ERROR: tokenserver 1.5.11 has requirement WebOb==1.8.5, but you'll have webob 1.4.1 which is incompatible.
> ```
> 
> The UWSGI executable might not be even be generated, causing the process to fail:
> 
> ```
> 2022-06-06 09:07:38,989: WARNING - Job for uwsgi-app@ffsync.service failed because the control process exited with error code.
> 2022-06-06 09:07:38,989: WARNING - See "systemctl status uwsgi-app@ffsync.service" and "journalctl -xe" for details.
> 2022-06-06 09:07:38,992: DEBUG - + ynh_exec_err journalctl --quiet --no-hostname --no-pager --lines=20 --unit=uwsgi-app@ffsync.service
> 2022-06-06 09:07:38,992: DEBUG - + [[ 6 -eq 1 ]]
> 2022-06-06 09:07:38,993: DEBUG - ++ journalctl --quiet --no-hostname --no-pager --lines=20 --unit=uwsgi-app@ffsync.service
> 2022-06-06 09:07:39,258: DEBUG - + ynh_print_err '--message=Jun 06 09:07:38 systemd[1]: Starting ffsync uWSGI app...
> 2022-06-06 09:07:39,284: DEBUG - Jun 06 09:07:38 systemd[3668036]: uwsgi-app@ffsync.service: Failed to locate executable /opt/yunohost/__app__/local/bin/uwsgi: No such file or directory
> 2022-06-06 09:07:39,284: DEBUG - Jun 06 09:07:38 systemd[3668036]: uwsgi-app@ffsync.service: Failed at step EXEC spawning /opt/yunohost/__app__/local/bin/uwsgi: No such file or directory
> 2022-06-06 09:07:39,285: DEBUG - Jun 06 09:07:38 systemd[1]: uwsgi-app@ffsync.service: Main process exited, code=exited, status=203/EXEC
> 2022-06-06 09:07:39,285: DEBUG - Jun 06 09:07:38 systemd[1]: uwsgi-app@ffsync.service: Failed with result '\''exit-code'\''.
> 2022-06-06 09:07:39,286: DEBUG - Jun 06 09:07:38 systemd[1]: Failed to start ffsync uWSGI app.'
> ```

Hello, it was a draft pull request, so it was really not ready to test !!! So it's why it don't worked

**Comment by Josue-T** [comment]
!testme

**Comment by Josue-T** [comment]
!testme

**Comment by Josue-T** [comment]
!testme

**Pull request merged**
